services:
  backend:
    build:
      context: ./djangobase2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend