version: "3.9"
services:
  backend:
    build:
      context: ./djangobase2/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
  
  nginx:
    container_name : nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always