# Generated by Django 4.2.9 on 2024-03-29 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=80)),
                ("content", models.TextField()),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "choice_subtask",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("단비", "단비"),
                            ("다래", "다래"),
                            ("블라블라", "블라블라"),
                            ("철로", "철로"),
                            ("땅이", "땅이"),
                            ("해태", "해태"),
                            ("수피", "수피"),
                        ],
                        max_length=80,
                        null=True,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("compleated_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="todo.task",
                    ),
                ),
            ],
        ),
    ]
