# Generated by Django 4.2.9 on 2024-02-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="subject",
            field=models.CharField(
                choices=[("일반", "일반"), ("정보", "정보"), ("사진", "사진"), ("자랑", "자랑")],
                default=1,
                max_length=80,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=80),
        ),
    ]
