# Generated by Django 4.2.9 on 2024-02-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_subject_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hits",
            field=models.IntegerField(default=0),
        ),
    ]
