# Generated by Django 4.2.9 on 2024-02-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_postimage_likecomment_likearticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likecomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_name",
                to="article.comment",
            ),
        ),
    ]
