name: Docekr CI

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Generate Environment Variables File for Production
        run: |
          touch .env
          echo AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> .env
          echo AWS_STORAGE_BUCKET_NAME=${{secrets.AWS_STORAGE_BUCKET_NAME}} >> .env
          echo DEBUG=${{secrets.DEBUG}} >> .env
          echo DATABASE_HOST=${{secrets.DATABASE_HOST}} >> .env
          echo DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} >> .env
          echo DATABASE_NAME=${{secrets.DATABASE_NAME}} >> .env
          cat .env
          ls -a