name: Docekr CI

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Generate Environment Variables File for Production
        run: |
          touch .env
          echo AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> .env
          echo AWS_STORAGE_BUCKET_NAME=${{secrets.AWS_STORAGE_BUCKET_NAME}} >> .env
          echo DEBUG=${{secrets.DEBUG}} >> .env
          echo DATABASE_HOST=${{secrets.DATABASE_HOST}} >> .env
          echo DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} >> .env
          echo DATABASE_NAME=${{secrets.DATABASE_NAME}} >> .env
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
          cat .env

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: sudo docker build -t mechauk418/drftest .
      - name: Push to Dockerhub
        run: sudo docker push mechauk418/drftest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop drftest
            sudo docker rm drftest
            sudo docker pull mechauk418/drftest
            sudo docker run --name drftest -p 443:8000 -d mechauk418/drftest