name: Docekr CI

on:
  push:
    branches: [master]

jobs: 
  deploy: 
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD    

      - name: Build the Docker image
        run: docker build -t mechauk418/drftest .
      - name: Push to Dockerhub
        run: docker push mechauk418/drftest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop drftest
            sudo docker rm drftest
            sudo docker pull mechauk418/drftest
            sudo docker run --name drftest -p 443:8000 -d mechauk418/drftest